;(function(window){'use strict';var support={transitions:Modernizr.csstransitions},transEndEventNames={'WebkitTransition':'webkitTransitionEnd','MozTransition':'transitionend','OTransition':'oTransitionEnd','msTransition':'MSTransitionEnd','transition':'transitionend'},transEndEventName=transEndEventNames[Modernizr.prefixed('transition')],onEndTransition=function(el,callback){var onEndCallbackFn=function(ev){if(support.transitions){if(ev.target!=this)return;this.removeEventListener(transEndEventName,onEndCallbackFn);}
if(callback&&typeof callback==='function'){callback.call(this);}};if(support.transitions){el.addEventListener(transEndEventName,onEndCallbackFn);}
else{onEndCallbackFn();}};function throttle(fn,delay){var allowSample=true;return function(e){if(allowSample){allowSample=false;setTimeout(function(){allowSample=true;},delay);fn(e);}};}
function nextSibling(el){var nextSibling=el.nextSibling;while(nextSibling&&nextSibling.nodeType!=1){nextSibling=nextSibling.nextSibling}
return nextSibling;}
function extend(a,b){for(var key in b){if(b.hasOwnProperty(key)){a[key]=b[key];}}
return a;}
function GridFx(el,options){this.gridEl=el;this.options=extend({},this.options);extend(this.options,options);this.items=[].slice.call(this.gridEl.querySelectorAll('.grid__item'));this.previewEl=nextSibling(this.gridEl);this.isExpanded=false;this.isAnimating=false;this.closeCtrl=this.previewEl.querySelector('button.action--close');this.previewDescriptionEl=this.previewEl.querySelector('.description--preview');this._init();}
GridFx.prototype.options={pagemargin:0,imgPosition:{x:1,y:1},onInit:function(instance){return false;},onResize:function(instance){return false;},onOpenItem:function(instance,item){return false;},onCloseItem:function(instance,item){return false;},onExpand:function(){return false;}}
GridFx.prototype._init=function(){this.options.onInit(this);var self=this;imagesLoaded(this.gridEl,function(){new Masonry(self.gridEl,{itemSelector:'.grid__item',isFitWidth:true});classie.add(self.gridEl,'grid--loaded');self._initEvents();self._setOriginal();self._setClone();});};GridFx.prototype._initEvents=function(){var self=this,clickEvent=(document.ontouchstart!==null?'click':'touchstart');this.items.forEach(function(item){var touchend=function(ev){ev.preventDefault();self._openItem(ev,item);item.removeEventListener('touchend',touchend);},touchmove=function(ev){item.removeEventListener('touchend',touchend);},manageTouch=function(){item.addEventListener('touchend',touchend);item.addEventListener('touchmove',touchmove);};item.addEventListener(clickEvent,function(ev){if(clickEvent==='click'){ev.preventDefault();self._openItem(ev,item);}
else{manageTouch();}});});this.closeCtrl.addEventListener('click',function(){self._closeItem();});window.addEventListener('resize',throttle(function(ev){self.options.onResize(self);},10));}
GridFx.prototype._openItem=function(ev,item){if(this.isAnimating||this.isExpanded)return;this.isAnimating=true;this.isExpanded=true;var gridImg=item.querySelector('img'),gridImgOffset=gridImg.getBoundingClientRect();this.current=this.items.indexOf(item);this._setOriginal(item.querySelector('a').getAttribute('href'));this.options.onOpenItem(this,item);this._setClone(gridImg.src,{width:gridImg.offsetWidth,height:gridImg.offsetHeight,left:gridImgOffset.left,top:gridImgOffset.top});classie.add(item,'grid__item--current');var win=this._getWinSize(),originalSizeArr=item.getAttribute('data-size').split('x'),originalSize={width:originalSizeArr[0],height:originalSizeArr[1]},dx=((this.options.imgPosition.x>0?1-Math.abs(this.options.imgPosition.x):Math.abs(this.options.imgPosition.x))*win.width+this.options.imgPosition.x*win.width/2)-gridImgOffset.left-0.5*gridImg.offsetWidth,dy=((this.options.imgPosition.y>0?1-Math.abs(this.options.imgPosition.y):Math.abs(this.options.imgPosition.y))*win.height+this.options.imgPosition.y*win.height/2)-gridImgOffset.top-0.5*gridImg.offsetHeight,z=Math.min(Math.min(win.width*Math.abs(this.options.imgPosition.x)-this.options.pagemargin,originalSize.width-this.options.pagemargin)/gridImg.offsetWidth,Math.min(win.height*Math.abs(this.options.imgPosition.y)-this.options.pagemargin,originalSize.height-this.options.pagemargin)/gridImg.offsetHeight);this.cloneImg.style.WebkitTransform='translate3d('+dx+'px, '+dy+'px, 0) scale3d('+z+', '+z+', 1)';this.cloneImg.style.transform='translate3d('+dx+'px, '+dy+'px, 0) scale3d('+z+', '+z+', 1)';var descriptionEl=item.querySelector('.description');if(descriptionEl){this.previewDescriptionEl.innerHTML=descriptionEl.innerHTML;}
var self=this;setTimeout(function(){classie.add(self.previewEl,'preview--open');self.options.onExpand();},0);onEndTransition(this.cloneImg,function(){imagesLoaded(self.originalImg,function(){classie.add(self.previewEl,'preview--image-loaded');self.originalImg.style.opacity=1;onEndTransition(self.originalImg,function(){self.cloneImg.style.opacity=0;self.cloneImg.style.WebkitTransform='translate3d(0,0,0) scale3d(1,1,1)';self.cloneImg.style.transform='translate3d(0,0,0) scale3d(1,1,1)';self.isAnimating=false;});});});};GridFx.prototype._setOriginal=function(src){if(!src){this.originalImg=document.createElement('img');this.originalImg.className='original';this.originalImg.style.opacity=0;this.originalImg.style.maxWidth='calc('+parseInt(Math.abs(this.options.imgPosition.x)*100)+'vw - '+this.options.pagemargin+'px)';this.originalImg.style.maxHeight='calc('+parseInt(Math.abs(this.options.imgPosition.y)*100)+'vh - '+this.options.pagemargin+'px)';this.originalImg.style.WebkitTransform='translate3d(0,0,0) scale3d(1,1,1)';this.originalImg.style.transform='translate3d(0,0,0) scale3d(1,1,1)';src='';this.previewEl.appendChild(this.originalImg);}
this.originalImg.setAttribute('src',src);};GridFx.prototype._setClone=function(src,settings){if(!src){this.cloneImg=document.createElement('img');this.cloneImg.className='clone';src='';this.cloneImg.style.opacity=0;this.previewEl.appendChild(this.cloneImg);}
else{this.cloneImg.style.opacity=1;this.cloneImg.style.width=settings.width+'px';this.cloneImg.style.height=settings.height+'px';this.cloneImg.style.top=settings.top+'px';this.cloneImg.style.left=settings.left+'px';}
this.cloneImg.setAttribute('src',src);};GridFx.prototype._closeItem=function(){if(!this.isExpanded||this.isAnimating)return;this.isExpanded=false;this.isAnimating=true;var gridItem=this.items[this.current],gridImg=gridItem.querySelector('img'),gridImgOffset=gridImg.getBoundingClientRect(),self=this;classie.remove(this.previewEl,'preview--open');classie.remove(this.previewEl,'preview--image-loaded');this.options.onCloseItem(this,gridItem);classie.add(this.originalImg,'animate');var win=this._getWinSize(),dx=gridImgOffset.left+gridImg.offsetWidth/2-((this.options.imgPosition.x>0?1-Math.abs(this.options.imgPosition.x):Math.abs(this.options.imgPosition.x))*win.width+this.options.imgPosition.x*win.width/2),dy=gridImgOffset.top+gridImg.offsetHeight/2-((this.options.imgPosition.y>0?1-Math.abs(this.options.imgPosition.y):Math.abs(this.options.imgPosition.y))*win.height+this.options.imgPosition.y*win.height/2),z=gridImg.offsetWidth/this.originalImg.offsetWidth;this.originalImg.style.WebkitTransform='translate3d('+dx+'px, '+dy+'px, 0) scale3d('+z+', '+z+', 1)';this.originalImg.style.transform='translate3d('+dx+'px, '+dy+'px, 0) scale3d('+z+', '+z+', 1)';onEndTransition(this.originalImg,function(){self.previewDescriptionEl.innerHTML='';classie.remove(gridItem,'grid__item--current');setTimeout(function(){self.originalImg.style.opacity=0;},60);onEndTransition(self.originalImg,function(){classie.remove(self.originalImg,'animate');self.originalImg.style.WebkitTransform='translate3d(0,0,0) scale3d(1,1,1)';self.originalImg.style.transform='translate3d(0,0,0) scale3d(1,1,1)';self.isAnimating=false;});});};GridFx.prototype._getWinSize=function(){return{width:document.documentElement.clientWidth,height:window.innerHeight};};window.GridFx=GridFx;})(window);